### ISSUE TITLE
Wrong Label Parameter for Address

### ISSUE THREAD

**Issue by HeinzKessler** [FolkerKinzel/VCards#5]
**Describe the bug**
Wrong Label Parameter for address

**To Reproduce**
Open the attached .vcf with the ParseVcf method using Windows-125 encoding.
The vcf contains 3 addresses and was created using MS Outlook.

**Expected behavior**
The "Label" property for the first of the three addresses should be "Business-Straße 19\r\n76543 Schaffhausen", matching the first address value
Instead the "Label" property is the same as of the 3rd address: "Sonstgasse 44\r\n37465 Anderstadt"

**Desktop (please complete the following information):**
 - OS: Windows 10 eng
 - .NET Version: .Net 4.8.1

**Additional context**
[Rudi Wimmel2 von Outlook.zip](https://github.com/FolkerKinzel/VCards/files/11747295/Rudi.Wimmel2.von.Outlook.zip)

P.S.: Sorry to bother you again! Heinz

**Comment by FolkerKinzel** [comment]
Thanks for posting the bug. It is fixed with Version 5. You can install the nuget package FolkerKinzel.VCards 5.0.0-beta.1 now.
